In [57]:
import pandas as pd

In [58]:
raw = pd.read_csv('/work/ExpP_2026/ExpPsyLing/combined_data.csv')

In [59]:
raw

,participant_id,component_num,url,meta,sender,sender_type,sender_id,ended_on,duration,time_run,...,response,response_action,prime,target,condition,soa_condition,congruence,correct_response,correctResponse,correct
0,51,1,NaN,NaN,Wecome1,canvas.Screen,1,timeout,499.56,3556.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51,1,NaN,NaN,Wecome2,canvas.Screen,2,timeout,499.52,4056.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51,1,NaN,NaN,Wecome3,canvas.Screen,3,timeout,499.52,4555.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,51,1,NaN,NaN,Instructions1,canvas.Screen,4,response,9061.10,5061.0,...,NaN,keypress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,51,1,NaN,NaN,Instructions 1a,canvas.Screen,5,response,2279.00,14148.0,...,NaN,keypress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15632,69,1,NaN,NaN,Short Loop,flow.Loop,12_1_0,completion,85426.00,131341.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15633,69,1,NaN,NaN,Break,canvas.Screen,12_1_1,response,868.30,216786.9,...,NaN,keypress(Space),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15634,69,1,NaN,NaN,Short Sequence,flow.Sequence,12_1,completion,86318.40,131341.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15635,69,1,NaN,NaN,Experiment Sequence,flow.Sequence,12,completion,183618.50,34044.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15636,69,1,NaN,NaN,root,flow.Sequence,NaN,completion,216385.18,1295.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
# raw.head(20)

In [61]:
# listing the column names
list(raw)

['participant_id',
 'component_num',
 'url',
 'meta',
 'sender',
 'sender_type',
 'sender_id',
 'ended_on',
 'duration',
 'time_run',
 'time_render',
 'time_show',
 'time_end',
 'time_commit',
 'timestamp',
 'time_switch',
 'response',
 'response_action',
 'prime',
 'target',
 'condition',
 'soa_condition',
 'congruence',
 'correct_response',
 'correctResponse',
 'correct']

In [62]:
# listing the columns that we need from the list
cols = ['participant_id','sender','duration','response', 'condition', 'soa_condition', 'congruence', 'correct_response', 'correct', "target"]

In [63]:
df = raw[cols]

In [64]:
df

,participant_id,sender,duration,response,condition,soa_condition,congruence,correct_response,correct,target
0,51,Wecome1,499.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51,Wecome2,499.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51,Wecome3,499.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,51,Instructions1,9061.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,51,Instructions 1a,2279.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
15632,69,Short Loop,85426.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15633,69,Break,868.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15634,69,Short Sequence,86318.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15635,69,Experiment Sequence,183618.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15636,69,root,216385.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
df = df[df["sender"] == "target"]

In [66]:
df

,participant_id,sender,duration,response,condition,soa_condition,congruence,correct_response,correct,target
13,51,target,843.38,n,practice,practice,practice,n,True,SHEEP
19,51,target,593.04,m,practice,practice,practice,m,True,BOAT
25,51,target,559.18,m,practice,practice,practice,m,True,HOUSE
31,51,target,653.76,n,practice,practice,practice,n,True,HORSE
40,51,target,520.14,m,Inc_Synth_Synth,long,incongruent,m,True,PIANO
...,...,...,...,...,...,...,...,...,...,...
15606,69,target,699.20,m,Con_Synth,short,congruent,m,True,BELT
15612,69,target,580.20,n,Con_Nat,short,congruent,n,True,DAISY
15618,69,target,577.90,m,Inc_Nat_Synth,short,incongruent,m,True,SHED
15624,69,target,661.10,n,Inc_Synth_Nat,short,incongruent,n,True,HUSKY
15630,69,target,709.20,n,Inc_Nat_Nat,short,incongruent,n,True,PETAL

In [67]:
sender_list = list(df["sender"])
set(sender_list)

{'target'}

In [68]:
df["sender"].unique()

<StringArray>
['target']
Length: 1, dtype: str

In [69]:
# df = raw(cols)
# df = df[df["sender"] == "target"]
df = df[df["condition"] != "practice"]
df = df.drop(columns = ["sender"])

In [70]:
df

,participant_id,duration,response,condition,soa_condition,congruence,correct_response,correct,target
40,51,520.14,m,Inc_Synth_Synth,long,incongruent,m,True,PIANO
47,51,640.66,n,Inc_Nat_Nat,long,incongruent,m,False,BULL
54,51,597.74,n,Inc_Synth_Nat,long,incongruent,n,True,GOAT
61,51,495.68,n,Con_Nat,long,congruent,n,True,PEAR
68,51,556.86,m,Inc_Nat_Synth,long,incongruent,m,True,MOTOR
...,...,...,...,...,...,...,...,...,...
15606,69,699.20,m,Con_Synth,short,congruent,m,True,BELT
15612,69,580.20,n,Con_Nat,short,congruent,n,True,DAISY
15618,69,577.90,m,Inc_Nat_Synth,short,incongruent,m,True,SHED
15624,69,661.10,n,Inc_Synth_Nat,short,incongruent,n,True,HUSKY
15630,69,709.20,n,Inc_Nat_Nat,short,incongruent,n,True,PETAL

In [71]:
# df ["accuracy"] = df ["response"] == df["correct_response"]
df.loc[df["target"] == "BULL", "correct_response"] = "n"

In [72]:
df

,participant_id,duration,response,condition,soa_condition,congruence,correct_response,correct,target
40,51,520.14,m,Inc_Synth_Synth,long,incongruent,m,True,PIANO
47,51,640.66,n,Inc_Nat_Nat,long,incongruent,n,False,BULL
54,51,597.74,n,Inc_Synth_Nat,long,incongruent,n,True,GOAT
61,51,495.68,n,Con_Nat,long,congruent,n,True,PEAR
68,51,556.86,m,Inc_Nat_Synth,long,incongruent,m,True,MOTOR
...,...,...,...,...,...,...,...,...,...
15606,69,699.20,m,Con_Synth,short,congruent,m,True,BELT
15612,69,580.20,n,Con_Nat,short,congruent,n,True,DAISY
15618,69,577.90,m,Inc_Nat_Synth,short,incongruent,m,True,SHED
15624,69,661.10,n,Inc_Synth_Nat,short,incongruent,n,True,HUSKY
15630,69,709.20,n,Inc_Nat_Nat,short,incongruent,n,True,PETAL

In [73]:
df["accuracy"] = df["response"] == df["correct_response"]

In [74]:
df

,participant_id,duration,response,condition,soa_condition,congruence,correct_response,correct,target,accuracy
40,51,520.14,m,Inc_Synth_Synth,long,incongruent,m,True,PIANO,True
47,51,640.66,n,Inc_Nat_Nat,long,incongruent,n,False,BULL,True
54,51,597.74,n,Inc_Synth_Nat,long,incongruent,n,True,GOAT,True
61,51,495.68,n,Con_Nat,long,congruent,n,True,PEAR,True
68,51,556.86,m,Inc_Nat_Synth,long,incongruent,m,True,MOTOR,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,m,Con_Synth,short,congruent,m,True,BELT,True
15612,69,580.20,n,Con_Nat,short,congruent,n,True,DAISY,True
15618,69,577.90,m,Inc_Nat_Synth,short,incongruent,m,True,SHED,True
15624,69,661.10,n,Inc_Synth_Nat,short,incongruent,n,True,HUSKY,True
15630,69,709.20,n,Inc_Nat_Nat,short,incongruent,n,True,PETAL,True

In [79]:
df_grouped = df.groupby(["soa_condition", "congruence"]).mean(["duration"])
df_grouped

ValueError: numeric_only accepts only Boolean values

In [75]:
df_grouped = df_grouped.reset_index()
df_grouped

NameError: name 'df_grouped' is not defined

In [76]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [77]:
ax = sns.barplot(data = df_grouped, x = "soa_condition", y = "duartion", hue = "soa_condition")

NameError: name 'sns' is not defined